### ISSUE TITLE
Unclear description of hexadecimal values?

### ISSUE THREAD

**Issue by FiniteReality** [nagisa/msi-rgb#101]
I've been playing around with this utility for a bit, since I have the MSI X370 SLI PLUS motherboard and I was curious if I could control my RGB lighting. However, it seems that the hexadecimal values are poorly explained.

When I run this command:
```
./msi-rgb -d 60 0F00FF0F F0F0F00F 00FF0F0F
```
I get a colour sequence of red, green, blue, cyan, magenta, yellow, white, black.

To me, this seems to suggest that the colours follow an 8-step pattern, where the nibbles of each byte are reversed. This means the order is `21436587`, and there are 16 different possible brightnesses for each colour.

Is it possible that the order of the steps could be fixed in code, or this be documented?

**Comment by nagisa** [comment]
The behaviour is hardware specific and changes between boards. Currently the data it writes to hardware is pretty much exactly what is specified on the command line – it is the user’s responsibility to figure out the particularities of their own hardware.

The behaviour will not be changed and documenting how exactly any particular board works is way out of scope for this project.
