### ISSUE TITLE
Leak? on MSI for mobo lights

### ISSUE THREAD

**Issue by stbatuhan** [nagisa/msi-rgb#12]
There is a leak i guess on msi website. There you can download Mystic Light Api sdk:

http://download.msi.com/uti_exe/Mystic_Light_2.zip

Maybe they can replace that link, then i can upload to GDrive. I didn't do that for now bec it's not of course safe to trust 3rd party guy for that (me) but i can only upload header and dll files with documentation pdf for be safe. That support would be awesome.

**Comment by nagisa** [comment]
I looked through it and it doesn’t really have anything useful there, that’s not available by other means.

Thanks anyway!
