### ISSUE TITLE
Could not Compile

### ISSUE THREAD

**Issue by SpiderPOH** [nagisa/msi-rgb#14]
root@M-7A32:~/Work/msi-rgb# cargo build --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling strsim v0.6.0
   Compiling ansi_term v0.10.2
   Compiling libc v0.2.34
   Compiling vec_map v0.8.0
   Compiling cc v1.0.3
   Compiling unicode-width v0.1.4
   Compiling cfg-if v0.1.2
   Compiling bitflags v1.0.1
   Compiling rustc-demangle v0.1.5
error: expected ident, found #
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.1/src/lib.rs:423:29
    |
423 |                             #[allow(deprecated)]
    |                             ^
    | 
   ::: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.1/src/example_generated.rs
    |
4   | bitflags! {
    | - in this macro invocation

error: Could not compile `bitflags`.
Build failed, waiting for other jobs to finish...
error: build failed

Whats wrong ?? i Don know where is the problem ?

Mainboard : MSI Gaming Pro Carbon X370
Super I/O Chip :  NUVOTON NCT6795D - M
iḿ Using xubuntu : Linux M-7A32 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nagisa** [comment]
What’s the output of `rustc --version`?

**Comment by SpiderPOH** [comment]
rustc --version
rustc 1.17.0

**Comment by nagisa** [comment]
You will need a more recent release of rustc toolchain to build this project.
