### ISSUE TITLE
Not working on MSI Computer X99A GAMING PRO CARBON A

### ISSUE THREAD

**Issue by CoyoteRay** [nagisa/msi-rgb#18]
Compile from source, when I ran the examples the following was returned:

./msi-rgb 206487a9 206487a9 10325476 -ir -ig -ib -d 5 
error: could not set the colour
    caused by: The sI/O chip identifies as c911, which does not seem to be NCT6795D
    caused by: `--ignore-check` flag, which would skip the check, is not specified (may be dangerous); also try `--base-port

Changed the base port to 2e as suggested in the help page, the following was returned:
./msi-rgb 206487a9 206487a9 10325476 -ir -ig -ib -d 5 --base-port 2e 
error: could not set the colour
    caused by: The sI/O chip identifies as ffff, which does not seem to be NCT6795D
    caused by: `--ignore-check` flag, which would skip the check, is not specified (may be dangerous); also try `--base-port`

**Comment by nagisa** [comment]
As the error message says:

>  caused by: The sI/O chip identifies as c911, which does not seem to be NCT6795D

If a visual inspection of the board reveals presence of a NCT6795D chip, please re-open the issue.
