### ISSUE TITLE
X370 Gaming Pro Carbon not working

### ISSUE THREAD

**Issue by OXiDE-dev** [nagisa/msi-rgb#24]
The default, 4e, only changes this LED:
![screenshot](https://user-images.githubusercontent.com/26662922/43005167-aa1fe89c-8c3a-11e8-8185-5a445830ee57.png)
I can disable it and make it pulse but that's it.

2e gives me this error and using `--ignore-check` doesn't change any LED:
![screenshot](https://user-images.githubusercontent.com/26662922/43005368-54634236-8c3b-11e8-9650-618ece185b6c.png)

**Comment by nagisa** [comment]
Goto #5.
