### ISSUE TITLE
MSI H310M Gaming Artic - RGB strip on "JLED1" connector

### ISSUE THREAD

**Issue by willierpt** [nagisa/msi-rgb#49]
Software doesn't appear to do anything on this board.
I am trying to connect a rgb strip to the JLED1 connector on the motherboard

**Comment by willierpt** [comment]
updt the MB name

**Comment by willierpt** [comment]
i realized i dindt provide enough evidence. i will investigate further.

**Comment by willierpt** [comment]
if there is any kind of information or procedure i could  give or do, ill be happy to assist

**Comment by nagisa** [comment]
Unless you’re willing to do the work of figuring out what Windows’ MSI app does, alas.

**Comment by willierpt** [comment]
> It is very possible that it just doesn’t work, or if it does work, it controls something else than JLED1.

I believe that second option is correct. because it doesn't spit any err on execution right after installation.
see https://pastebin.com/fi6Tv1kL

As soon as make any change to the terminal or computer it just spits out a segmentation fault. (not sure if relevant)

**Comment by willierpt** [comment]
[https://i.imgur.com/6ixCMpn.jpg](url) 

Turns out this MB super i/o chip is diferent.

 Sorry for the trouble.
