### ISSUE TITLE
Failed to build error

### ISSUE THREAD

**Issue by dapmeup** [nagisa/msi-rgb#53]
Hi. I am new to this so hopefully it is me and not the code. I installed Git, Rust, Cargo, and GCC on my machine and then followed the steps provided from this site.  I received a failed to build error and cannot tell if it is my machine or the code.  I have no idea what all this means.  I am running Solus 3.999 with Budgie. 

[Failed_To_Buid_MSIRGB.txt](https://github.com/nagisa/msi-rgb/files/2815153/Failed_To_Buid_MSIRGB.txt)

**Comment by nagisa** [comment]
You are missing necessary headers. I know nothing about Solus, so you will have to figure out what package provides those headers yourself.

**Comment by nagisa** [comment]
Namely the missing header is `linux/errno.h`.

**Comment by dapmeup** [comment]
Thanks!  It turned out for Solus I had to install `system.devel` to get the all development tools.  It now builds but doesn't work with the commands. (i.e. `sudo ./target/release/msi-rgb 00000000 FFFFFFFF 00000000`).  The pain of being a noob. 

~/msi-rgb $ cargo build --release
   Compiling backtrace-sys v0.1.28
   Compiling atty v0.2.11
   Compiling term_size v0.3.1
   Compiling clap v2.23.3
   Compiling backtrace v0.3.13
   Compiling error-chain v0.12.0
   Compiling msi-rgb v0.1.0 (/home/shannon/msi-rgb)
    Finished release [optimized] target(s) in 22.80s
