### ISSUE TITLE
MSI B450 Tomahawk - Colors do not match

### ISSUE THREAD

**Issue by mojtabamozaffar** [nagisa/msi-rgb#63]
I have an MSI B450 Tomahawk and trying to figure out how to work with this tool as it behaves differently from the instructions in README.

For me the output of msi-rgb FFFFFFFF 00000000 00000000 alternates between blue and white, the output of msi-rgb 00000000 FFFFFFFF 00000000 alternates between purple and white, and the output of the msi-rgb 00000000 00000000 FFFFFFFF alternates between yellow and white. 

Other than the fact that I expect different colors to be displayed, I expect the color to be fixed and not changing between different ones.

Does anyone have any suggestions on how to configure the program to show the correct colors and to stop it from changing it?

**Comment by dcerisano** [comment]
Try initializing the B450 with the MSI Gaming App (turn LEDs on).
You will have to boot WIN to do this.

**Comment by mojtabamozaffar** [comment]
Thanks for the response. But isn't not having/wanting to install Windows the reason for using this code. Is it possible to use a virtual environment, wine, or playonlinux for to do the initial setup?

**Comment by nagisa** [comment]
> But isn't not having/wanting to install Windows the reason for using this code.

This is quite spot-on, but it is also the case that the only *really* supported board is my own, and the rest of the boards were only reported as working by other people. I’m unable to provide support nor fix the code for other boards and what @dcerisano suggests is a troubleshooting suggestion, I guess.

> Is it possible to use a virtual environment, wine, or playonlinux to do the initial setup?

No.

**Comment by mojtabamozaffar** [comment]
@nagisa Thanks for your timely answer. It makes perfect sense. Just as a suggestion, if you have any instructions or useful resources on how one can develop such code with some slight details, I am sure there are many people, including myself, that are willing to spend time to extend this library so that it works properly on a wide range of motherboards.

**Comment by nagisa** [comment]
There is something you can use as a starting point described in [my blog post linked from the README](https://kazlauskas.me/entries/i-reverse-engineered-a-motherboard.html). I know that https://github.com/ixjf has quite successfully decompiled the MSI code and using msi-rgb as an inspiration made a C# application as well.

In general helping out involves running windows on bare-metal and then looking at how the MSI’s official app behaves with some particular hardware, but perhaps checking whether alternative apps work and cross-referencing code paths would also help.

**Comment by dcerisano** [comment]
As @nagisa stated, msi-rgb is only guaranteed to run on one mobo (MSI Mortar Arctic).
For many others, the WIN based MSI app must be run once per power cycle to init the RGB header.
Also, running the MSI app via WINE is a no go.
