### ISSUE TITLE
Support for Asus TUF B450 Gaming Plus

### ISSUE THREAD

**Issue by a-wigand** [nagisa/msi-rgb#64]
The **MSI B450 GAMING PLUS AC** board is listed under the working boards.
The **Asus TUF B450 Gaming Plus** board has the same chipset ([specs](https://www.asus.com/Motherboards/TUF-B450-PLUS-GAMING/specifications/)).
After compiling and running `sudo ./target/release/msi-rgb 00000000 FFFFFFFF 00000000`  
however, I get the following error:
```
error: could not set the colour
    caused by: The sI/O chip identifies as ffff, which does not seem to be NCT6795D
    caused by: `--ignore-check` flag, which would skip the check, is not specified (may be dangerous); also try `--base-port`
```
As I don't know what *may be dangerous* means, I would like to know if someone could help me with that problem.

**Comment by nagisa** [comment]
RGB header is controlled by the Super I/O chip, not the "chipset". This tool won’t work on ASUS boards.

**Comment by a-wigand** [comment]
Thank you for the quick reply.

**Comment by CalcProgrammer1** [comment]
For ASUS boards, try my OpenAuraSDK project.  Aura works quite differently from MSI.

https://gitlab.com/CalcProgrammer1/OpenAuraSDK
