### ISSUE TITLE
On an unrelated note: We may be able to now control the chipset fan of MSI x570

### ISSUE THREAD

**Issue by Overc1ocker** [nagisa/msi-rgb#78]
The new MSI Dragon Center software includes a few DAT files called "Chipsetfan". It contains a board id, 3 fan "modes"

**Comment by Overc1ocker** [comment]
Renamed to .txt so github would upload it
[ChipsetFan.txt](https://github.com/nagisa/msi-rgb/files/3570681/ChipsetFan.txt)

**Comment by flying-sheep** [comment]
an earlier bug seems to be #71

**Comment by nagisa** [comment]
Well this one is about the fan, but since this tool is not about fans, closing as out-of-scope.

**Comment by flying-sheep** [comment]
oh, whoops
