### ISSUE TITLE
One RGB Fan is not the same Color as other

### ISSUE THREAD

**Issue by D1Ck3n** [nagisa/msi-rgb#84]
Hello,

I have the following problem with a fan in my Sharkoon TG5 RGB case: All fans and RGB Stripe can be addressed correctly, but one of the front fans always has a different color.

Can this be due to the software or do I have to contact the manufacturer because of hardware errors?

Greetings
![IMG_20191017_204240](https://user-images.githubusercontent.com/28949322/67040372-ab346d80-f123-11e9-8df6-64ff67dd1fb1.jpg)

**Comment by nagisa** [comment]
Seeing as the fans are set to "white"-ish, that would suggest the fan is either not plugged in all the way or there’s no electrical contact between the ground pin and red/blue channels.

Seeing as you have plugged all of your stuff into the same RGB port, I would suspect that the fan or cabling is bad, but you will have to figure out the cause yourself.

**Comment by D1Ck3n** [comment]
thanks for the hint of a defective cable! that was the issue.
