### ISSUE TITLE
Request to support MSI X570 Aorus Master 

### ISSUE THREAD

**Issue by ashwinmj** [nagisa/msi-rgb#89]
Tried running the project after following the instructions mentioned in the [README](https://github.com/nagisa/msi-rgb/blob/master/README.md). Failed to set the colors.

Command issued -
`sudo ./target/release/msi-rgb 00000000 FFFFFFFF 00000000`

Received response -
`error: could not set the colour`
`    caused by: The sI/O chip identifies as ffff, which does not seem to be NCT6795D`
`    caused by: '--ignore-check' flag, which would skip the check, is not specified (may be dangerous); also try '--base-port'`

**Comment by flying-sheep** [comment]
duplicate of #71
