### ISSUE TITLE
Better handling of inversion on B450M Mortar

### ISSUE THREAD

**Issue by chintal** [nagisa/msi-rgb#91]
#23, #79 suggest the colors on the B450M Mortar are inverted.

Indeed, using -ir -ib -ig does produce the expected output. Specifically, inverting the state of -ir, -ib, -ig from the examples generates more or less the demonstrated output. It would be nice if this inversion could be auto detected based on motherboard id. A lot of work, I know, but is a pretty big leap if you're a new user.

Additionally, there might be some corner cases in the actual inversion due to which it is not exactly correct. When compared to the example images, I notice the following notable differences :

  -  Heartbeat doesn't seem to do anything at all
  -  Police has long (2 seconds or so maybe) gaps between the blue and red. It follows a sequence of blue - blue - red - red
  - Hue wheel has the LEDs off for significant periods, maybe about 60% on 40% off

Could there be other non-color bits n the registers which are not exactly inverted which are causing this variation?

**Comment by nagisa** [comment]
Most likely what is happening here is that the bitfields are incompatible between motherboards even with the same chipset.

**Comment by westjgames** [comment]
#73
