### ISSUE TITLE
Cant change color

### ISSUE THREAD

**Issue by D1Ck3n** [nagisa/msi-rgb#94]
Hi,

I tried to get the color to static red, but unfortunately nothing changes. for me the color always changes between, purple, green and yellow. actually something seems to work, because i can switch off the RGB with msi-rgb -x 00000000 000000 00000000 00000000.

do you have any idea?

my specs:
CPU: Ryzen 5 2600X
Motherboard: MSI B450 Tomahawk
Host Kernel version: 5.3

**Comment by macgherl57** [comment]
Hi!
I have the exact same mainboard. Please see, if you haven't already, #92...
msi-rgb 0 0 0 -ir -ib -> green
msi-rgb 0 0 0 -ir- ig -> blue
msi-rgb 0 0 0 -ib -ig -> red
Inverting the colours does the trick.
Some other interesting suggestion in #92 as well.

**Comment by D1Ck3n** [comment]
Hi macgherl57,

thank you very much!! you are my hero! :)
cheers!
